org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
forge_version=47.4.10
forge_version_range=[47.4.0,)
curios_version=5.14.1+1.20.1
curios_version_range=[5.14.1,)
epicfight_version=20.13.6
epicfight_version_range=[20.13.6,)
mod_id=epicfight_curios_compat
mod_name=EpicFight x Curios Compat
mod_version=1.4
mod_group_id=com.oneworldstudio.epicfightcurioscompat
mod_license=Apache-2.0
mod_authors=Unitei
mod_credits=One World Studio 2019-2026
mod_display_url=https://github.com/OneWorldStudio-Unitei/OneWorldStudio_EpicFight_CuriosCompat
mod_description=Standalone Curios compatibility for EpicFight with per-slot transforms, backpack bridges, and Curious Lanterns light handling.
