modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"
[[mods]]
modId="epicfight_curios_compat"
version="${file.jarVersion}"
displayName="EpicFight x Curios Compat"
credits="One World Studio 2019-2026"
displayURL="https://github.com/OneWorldStudio-Unitei/OneWorldStudio_EpicFight_CuriosCompat"
authors="Unitei"
description='''
Standalone Curios compatibility for EpicFight with per-slot transforms, backpack bridges, and Curious Lanterns light handling.
'''
[[dependencies.epicfight_curios_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicfight_curios_compat]]
    modId="curios"
    mandatory=true
    versionRange="[5.14.1,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.epicfight_curios_compat]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.13.6,)"
    ordering="AFTER"
    side="CLIENT"
